  {
    id: "echoes-solitude-01",
    title: "Echoes of Solitude - 1",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-01.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-02",
    title: "Echoes of Solitude - 2",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-02.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-03",
    title: "Echoes of Solitude - 3",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-03.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-04",
    title: "Echoes of Solitude - 4",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-04.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-05",
    title: "Echoes of Solitude - 5",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-05.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-06",
    title: "Echoes of Solitude - 6",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-06.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-07",
    title: "Echoes of Solitude - 7",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-07.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-08",
    title: "Echoes of Solitude - 8",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-08.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-09",
    title: "Echoes of Solitude - 9",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-09.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-10",
    title: "Echoes of Solitude - 10",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-10.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-11",
    title: "Echoes of Solitude - 11",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-11.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-12",
    title: "Echoes of Solitude - 12",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-12.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-13",
    title: "Echoes of Solitude - 13",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-13.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-14",
    title: "Echoes of Solitude - 14",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-14.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-15",
    title: "Echoes of Solitude - 15",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-15.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-16",
    title: "Echoes of Solitude - 16",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-16.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-17",
    title: "Echoes of Solitude - 17",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-17.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-18",
    title: "Echoes of Solitude - 18",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-18.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-19",
    title: "Echoes of Solitude - 19",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-19.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-20",
    title: "Echoes of Solitude - 20",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-20.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-21",
    title: "Echoes of Solitude - 21",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-21.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-22",
    title: "Echoes of Solitude - 22",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-22.png",
    section: "echoes",
  },
  {
    id: "echoes-solitude-23",
    title: "Echoes of Solitude - 23",
    year: "2023",
    medium: "Archival Print from PDF Documentation",
    description: "From the Echoes of Solitude exhibition documentation, capturing the layered narratives of female resilience and persistence.",
    image: "/images/echoes-solitude-23.png",
    section: "echoes",
  },
  {
    id: "whispers-trees-01",
    title: "Whispers From Ancient Trees - 1",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-01.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-02",
    title: "Whispers From Ancient Trees - 2",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-02.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-03",
    title: "Whispers From Ancient Trees - 3",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-03.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-04",
    title: "Whispers From Ancient Trees - 4",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-04.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-05",
    title: "Whispers From Ancient Trees - 5",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-05.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-06",
    title: "Whispers From Ancient Trees - 6",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-06.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-07",
    title: "Whispers From Ancient Trees - 7",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-07.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-08",
    title: "Whispers From Ancient Trees - 8",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-08.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-09",
    title: "Whispers From Ancient Trees - 9",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-09.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-10",
    title: "Whispers From Ancient Trees - 10",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-10.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-11",
    title: "Whispers From Ancient Trees - 11",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-11.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-12",
    title: "Whispers From Ancient Trees - 12",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-12.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-13",
    title: "Whispers From Ancient Trees - 13",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-13.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-14",
    title: "Whispers From Ancient Trees - 14",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-14.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-15",
    title: "Whispers From Ancient Trees - 15",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-15.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-16",
    title: "Whispers From Ancient Trees - 16",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-16.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-17",
    title: "Whispers From Ancient Trees - 17",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-17.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-18",
    title: "Whispers From Ancient Trees - 18",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-18.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-19",
    title: "Whispers From Ancient Trees - 19",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-19.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-20",
    title: "Whispers From Ancient Trees - 20",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-20.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-21",
    title: "Whispers From Ancient Trees - 21",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-21.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-22",
    title: "Whispers From Ancient Trees - 22",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-22.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-23",
    title: "Whispers From Ancient Trees - 23",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-23.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-24",
    title: "Whispers From Ancient Trees - 24",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-24.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-25",
    title: "Whispers From Ancient Trees - 25",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-25.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-26",
    title: "Whispers From Ancient Trees - 26",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-26.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-27",
    title: "Whispers From Ancient Trees - 27",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-27.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-28",
    title: "Whispers From Ancient Trees - 28",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-28.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-29",
    title: "Whispers From Ancient Trees - 29",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-29.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-30",
    title: "Whispers From Ancient Trees - 30",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-30.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-31",
    title: "Whispers From Ancient Trees - 31",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-31.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-32",
    title: "Whispers From Ancient Trees - 32",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-32.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-33",
    title: "Whispers From Ancient Trees - 33",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-33.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-34",
    title: "Whispers From Ancient Trees - 34",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-34.png",
    section: "whispers",
  },
  {
    id: "whispers-trees-35",
    title: "Whispers From Ancient Trees - 35",
    year: "2024",
    medium: "Archival Print from Brochure Documentation",
    description: "From the Whispers From Ancient Trees exhibition, documenting the traditional Igbo wooden sleeping mat exploration and its cultural significance.",
    image: "/images/whispers-trees-35.png",
    section: "whispers",
  },